### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by Divoolej** [newtack/redux-utils#5]
Hello @newtack @thomas-jeepe 
It's been over a month since I submitted a PR here and I see nothing has changed. I'd like to volunteer for a maintainer if it's possible. Please let me know what you think.

**Comment by thomas-jeepe** [comment]
Go ahead, I haven't been putting any work into this and haven't been using redux. My bad on not putting somewhere that this isn't maintained.

So I'll make you a maintainer and just let me know if anything else is needed
